### ISSUE TITLE
No pile-up of reads seen except MT genome

### ISSUE THREAD

**Issue by akhst7** [imilne/tablet#9]
Hi, 

I am trying to visualize read pileup of our mouse RNAseq bam flle by using the latest mouse primary assembly from Ensembl, `Mus_musculus.GRCm38.dna.primary_assembly.fa`, however I don't see any pileup nor DNA sequence in color except MT. I'd appreciate any inputs to solve this issue. 

thanks.

**Comment by mb47** [comment]
Hi,
the first thing to check here would be that there is no mismatch between the names of reference sequence contigs/chromosomes between your BAM file and the FASTA file you are using in Tablet. Typically this kind of problem is usually related to that. 
Micha

**Comment by peterjc** [comment]
I would guess you have GRCm38 and some other version of the mouse genome, but they happen to have the exact same mitochondria genome so that's the only reference sequence which is consistent.

Have a look at the exact names in your FASTA file,

```
$ grep "^>" Mus_musculus.GRCm38.dna.primary_assembly.fa
```

Do they match the reference names in your BAM file?

```
$ samtools idxstats your_file.bam
```

This will also confirm if you have reads mapped to all the chromosomes, or just the MT (which would be strange but would also explain the results).
